### ISSUE TITLE
_identify and _version

### ISSUE THREAD

**Issue by tehn** [monome/crow#129]
minor rework of https://github.com/monome/crow/issues/30

`_version()` should print just the software version (which can be stored as a var/string wherever, doesn't matter)

`_identify()` should return `crow [serial-number]` where the serial number is taken from the STM

on connection, a host will send `_identify()` as text to the tty device and have a timeout period waiting for a response that has "crow" at the front, for correct id as a crow.

**Comment by trentgill** [comment]
would it be weird to use `^^identify`? i only ask because it makes implementation easier (i don't have to plumb the serial# through lua). both of these commands seem to be 'remote-only' in that they are meaningless within the crow lua env. they only make sense coming from a remote host, so treating them as commands seems easier.

happy to implement either way, just let me know!

**Comment by tehn** [comment]
oh yes that's fine and smart!
