### ISSUE TITLE
Refine prints when crow is booted / restarted

### ISSUE THREAD

**Issue by trentgill** [monome/crow#217]
Currently when crow restarts there are a bunch of prints as each library is successfully loaded in the Lua environment. These are pretty much always the same & I've never seen them fail apart from a bogus firmware. Consider that if anything they should be 'debug' prints that aren't in the release version of the firmware.

Instead, does it make sense to print something when crow is booted, or after `^^k`, or after a new program is run/uploaded with `^^s` and `^^w/e`? This could be similar to `^^p` where it can say:
1. 'First' running
2. No user script running
3. User script running

If we wanted to get fancy, the user script could print the first line of the uploaded file (if it's a comment with three dashes) as this is likely the name of the script.

**Comment by simonvanderveldt** [comment]
Good points/questions!

From messing around within druid a bit I'd very much like to see something along the lines of `Running script <scriptname>` when you execute `r` or `u`. Not sure if it's possible for both and I'm aware we're currently unable to do this because we don't send the script name over (and the script name is irrelevant on crow because there's no filesystem).

It would already be an enhancement if a generic `User script running`/`No user script`/`First running` would be shown.
The idea to print the first line of the script sounds interesting but it would obviously depend on the script writer to put something meaningful there. Not sure if we an rely on that.

Also +1 on switching the `lua bootstrapped`, `input loaded`, etc output to debug output. Seems to be just noise for a regular user. It might just raise more questions (for example, I don't know why there's an `asl` as well as an `asllib` loaded).

It might still be useful to add a generic startup message when it's starting up and maybe also one when it's done initializing before loading the script so the user knows what's going on/that something is happening and in case something doesn't work it's a bit easier to pinpoint (startup vs script).
