### ISSUE TITLE
Amplitude tracking for inputs

### ISSUE THREAD

**Issue by trentgill** [monome/crow#242]
Currently the inputs just pass their literal voltage level. Would it be useful to have amplitude tracking of the input. We can use `VU_step()` from wrLib/wrMeters.h (cheap, slewed, sum-of-squares).

For 'stream' mode the voltage value becomes an envelope follower.
- Pass amplitude to an output to use crow as an env.follower
- Have a crow script param updated by the volume of a received signal

For 'change' mode it becomes an amplitude triggered event.
- Attach the output of a drum module, or other audio source and create crow events on trigger.
- 'threshold', 'hysteresis' & 'direction' all apply to the amplitude.

//

There are 2 different approaches I'm considering:

1. Make a stateful switch that selects 'voltage' or 'amplitude'
This would mean we keep all the other behaviour but just change the meaning of a read value. stream & change are identical but the data the use/return is different.  Implementation is easier, but means there is a potentially confusing state-switch something like:
`input[n].process = <val>`
where `<val>` is:
- 'none' or 'volts' for standard operation
- 'amplitude' for volume tracking
- could be extended to 'pitch' (though i don't know it's possible at the slow samplerate)

2. Additional events for amp_stream and amp_change.
This leads to less confusion but makes for an increased set of syntax & functions to learn. These events would be additions to the existing `input[n].mode` list. Additionally there would be a getter for `input[n].amplitude` which would return the current amplitude (like `input[n].volts`).
`amp_stream` isn't strictly necessary as the user could just set `input[n].mode('stream')` then change the callback to `input[n].stream = function() print(input[n].amplitude) end`.

**Comment by whimsical-sam** [comment]
My 2c:

I think that both strategies make sense from a conceptual standpoint.  

From a user perspective, these are the mental model differences: 
- (stateful switch) 1 input goes to two destinations (input processor) which then goes to two destinations (stream/change)
- (additional events) 1 input goes to four destinations (each of the modes)

1. Stateful switch
- I think presenting it as an additional option similar to e.g. threshold direction specified when initializing an input is pretty clear to an end-user if the naming of the key and modes is chosen carefully; one question would be if the same `processor` key is used for both `change` and `stream`, or if the two modes check separate keys. 
- an advantage I see to this method is that it makes it easy for a user to quickly adapt any script to accept audio input without/remembering much about the script; you can just execute `input[n].processor = 'env-follower'` and you are done. 
- I actually think that this approach fits a typical mental model of crow more than the other approach; using the envelope follower does not fundamentally change the stream or change events, just the data fed to them.  As such, in a configuration ierarchy, it does seem like a suboption rather than superoption of the input mode. Having said that...

2. Additional events: 
- I think you are right that this is pretty easy to grasp since it just extends the mental model of crow's modes, rather than reconfigures it.  
- It does make it slightly more difficult (maybe?) to adapt a script to accept audio - you either need to know the name of the function assigned to the standard stream/change callback and assign it to the amp version (not necessarily the case when using someone else's script), or you need to understand that you could copy the normal callback into the amp version's callback:
```
input[n].amp_stream = input[n].stream --or named function if known
input[n].mode('amp_stream',0.1)
```
- could be done in one line with a table call, but that gets clunky as well...

---

I think the clunkiness of switching from cv to audio with the additional events indicates that the stateful switch makes more sense to me, since I could see a really common use case being "hey I like this script, but what if I drove it with an audio signal??" from a creative standpoint, I think the stateful switch's ease of switching should be considered a big bonus!
